
import Image from "next/image";
import dataSlider from "./slider-data.json";
import MySlider from "@/components/MySlider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
   <>
    {/* <DemoSlider data={dataSlider} /> */}
    <MySlider />
    <div className="my-10">
      <h1>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
    </div>
   </>
  );
}
